site: Sean Voisen
url: https://sean.voisen.org
title: Sean Voisen
description: Writing about software design, development, and how computers shape what it means to be human.
author:
  name: Sean Voisen
twitter:
  username: svoisen
  card: summary

markdown: kramdown
highlighter: rouge

permalink: pretty

pagination:
  enabled: true
  per_page: 10
  permalink: "/:num/"
  title: ":title"
  sort_reverse: true

baseurl: ""

sass:
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

plugins:
  - jekyll-paginate-v2
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

feed:
  path: /atom.xml
  collections:
    notes:
      path: /notes/feed.xml

reading_time:
  second_plural: "second read"
  minute_singular: "minute read"
  minute_plural: "minute read"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slugified_categories/:slug
  notes:
    output: true
    permalink: /notes/:year-:month-:day-:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      type: "pages"
    values:
      layout: "page"
  - scope:
      type: "posts"
    values:
      layout: "post"
  - scope:
      type: "notes"
    values:
      layout: "note"
  - scope:
      path: "assets/images"
    values:
      image: true

navigation:
  - text: Marginalia
    url: /marginalia/
  - text: Blog
    url: /blog/
  - text: Notes
    url: /notes/
  - text: Bookshelf
    url: /bookshelf
  - text: About
    url: /about/
