markdown: rdiscount
highlighter: pygments
permalink: /blog/:year/:month/:title/
title: Sean Voisen
navigation:
  - text: About
    title: About me
    url: /about/
  - text: Writing
    title: Blog archives
    url: /blog/
  - text: Reading
    title: Book reviews
    url: /reading/
  - text: Projects
    title: Various side projects
    url: /projects/
  - text: Now
    title: Aspirations for the present moment
    url: /now/