site: Sean Voisen
url: https://sean.voisen.org
title: Sean Voisen
description: Sean Voisen is trying to make computing more humane, convivial and creative.
author:
  name: Sean Voisen
twitter:
  username: svoisen
  card: summary

markdown: kramdown
highlighter: rouge

permalink: pretty

paginate: 1000
paginate_path: "/page:num/"
baseurl: ""
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  projects:
    output: true
    permalink: /projects/:slug
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - 
    scope:
      path: "assets/images"
    values:
      image: true

navigation:
  - text: About
    title: About the author.
    url: /about/
  - text: Writing
    title: Blog posts, essays and other writings.
    url: /writing/
  - text: Reading
    title: My personal library.
    url: /reading/