site: Sean Voisen
url: https://sean.voisen.org
title: Sean Voisen
description: Spurious thoughts on making computing better for humans.
author:
  name: Sean Voisen
twitter:
  username: svoisen
  card: summary

markdown: kramdown
highlighter: rouge

permalink: pretty

paginate: 1000
paginate_path: "/page:num/"
baseurl: ""

sass:
  style: compressed
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap  
  - jekyll-og-image
  - jekyll-feed
  # - jekyll-minifier

feed:
  path: /atom.xml
  collections:
    notes:
      path: /notes/feed.xml

reading_time:
  second_plural: "second read"
  minute_singular: "minute read"
  minute_plural: "minute read"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /writing/:slug
  reading:
    output: true
    permalink: /reading/:slug
  notes:
    output: true
    permalink: /notes/:year-:month-:day-:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      type: "reading"
    values:
      layout: "book"
  -
    scope:
      type: "notes"
    values:
      layout: "note"
  - 
    scope:
      path: "assets/images"
    values:
      image: true

navigation:
  - text: About
    url: /about
    overflow: false
  - text: Writing
    url: /writing
    overflow: true
  - text: Notes
    url: /notes
    overflow: true

jekyll-minifier:
  uglifier_args:
    harmony: true

og_image:
  output_dir: "/assets/images"
  image: "/assets/images/sean_voisen@512.jpg"
  # domain: "sean.voisen.org"
  canvas:
    # background_image: "/assets/images/og_background_svoisen.jpg"
    background_color: "#002d38"
  header:
    font_family: "SF Pro Text Bold"
    color: "#f1e9d2"
  content:
    font_family: "SF Pro Text"
    color: "#8faaab"
  force: false
  border_bottom:
    width: 10
    fill:
      - "#ac8300"
      - "#d56500"
      - "#f23749"
      - "#dd459d"
      - "#2b90d8"
