source 'http://rubygems.org'
gem 'jekyll'
gem 'jekyll-paginate'
gem 'jekyll-gist'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jekyll-minifier'
gem 'jekyll-feed'
gem 'jekyll-og-image', :git => 'https://github.com/svoisen/jekyll-og-image'
gem 'jammit'
gem 'rouge'
gem 'webrick'
gem 'liquid', '4.0.4'
