source 'http://rubygems.org'
gem 'jekyll'
gem 'jekyll-paginate-v2'
gem 'jekyll-gist'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jekyll-minifier'
gem 'jekyll-feed'
gem 'jammit'
gem 'rouge'
gem 'webrick'
gem 'liquid', '4.0.4'
gem 'csv'
gem 'base64'
